monolog:
    channels: ['uploading']
    handlers:
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        exporter:
            level: info
            type: stream
            path: '%kernel.logs_dir%/aquis_xporter.log'
            channels: [aquis_xporter]
